### PR TITLE
Make edit menu work

### LINKED ISSUE #38: paste breaks format
When I paste multi line code from the browser into nyaovim it breaks the formatting regardless of 'set paste'
### Expected Behavior

I expect it the text to look like the one I pasted instead of everything on a single line
### Actual Behavior

All the text is paste into a single line

### Steps to Reproduce (including precondition)

grab some text like this
screenshot 2016-03-17 16 22 25

from 
http://docs.ansible.com/ansible/playbooks_prompts.html

open nyaovim and enter insert mode
paste in the text from your clipboard

### Screenshot on This Problem (if possible)

screenshot 2016-03-17 16 25 45

### Your Environment

- OS: Mac OSX 10.11.4 Beta (15E61b)
- NyaoVim version: NyaoVim version 0.0.19
  electron : 0.36.11
  chrome : 47.0.2526.110
  node : 5.1.1
  v8 : 4.7.80.27
- Keyboard layout: US

### LINKED ISSUE #61: copy to system clipboard?
I'm wondering if it's possible to place text into the clipboard by selecting it in visual mode then doing cmd+c (I'm on a mac), similar to the way this works in [Neovim.app](https://github.com/rogual/neovim-dot-app). I'm assuming that either this isn't currently supported, or I've done something odd in my environment that is preventing this from working.

### Expected Behavior

the visual-mode selected text is not copied to the system clipboard.

### Actual Behavior

it should be copied to the system clipboard.

### Steps to Reproduce (including precondition)

1. copy some text from anywhere except Nyaovim into the system clipboard (for reference).
2. in Nyaovim, select some text with visual mode.
3. in the Nyaovim's Edit menu, click on Copy, or press cmd+c.
4. in any window, attempt to paste this text. You'll see that it's the text from step 1, not step 3.

### Your Environment

- OS: Mac OS 10.11.6 beta
- NyaoVim version: 0.0.19
- `nvim` version: v0.1.5-564-g6cee9d1
- Keyboard layout: Apple

### PR DESCRIPTION
**Pull request by haifengkao**
### What was a problem?

- support system clipboard (#61)
- fix paste breaks format (#38)
- make undo and redo in edit work

### How this PR fixes the problem?

When a user presses cmd+c, v, a, x, or z, NyaoVim will execute the corresponding vi command instead of the default Electron actions.

### Check lists (check `x` in `[ ]` of list items)

- [x] Coding style (if any code was modified)
- [x] Confirmed
  - OS: {OSX 10.11}
  - `nvim` version: {0.1.5}

### Additional Comments (if any)

close #61
close #38

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you for the contributions!  I'll review.

File: renderer/nyaovim-app.ts [hunk 1]
```diff
@@ -164,6 +164,117 @@ Polymer({
                     client.command(c);
                 }
             });
+
+            ipc.on('nyaovim:copy', (_: Electron.IpcRendererEvent) => {
+                // get current vim mode
+                var m = client.commandOutput('echo mode()');
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: I think `client.eval('mode()')` should also work and prefers to `commandOutput()` for this purpose.

File: renderer/nyaovim-app.ts [hunk 2]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+                m.then(value => {
+                    //  mode() returns a strange '\n' at the beginning, why?
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: That's a spec of Vim.  All vim commands' outputs start with `\n`.  For example, `:echo blah` outputs `\nblah` (unlike other popular scripts, Vim adds newline to the head of output.)

File: renderer/nyaovim-app.ts [hunk 3]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+                    value = value.trim();
+                    if (value.length > 0) {
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: Please use early return.

```javascript
if (value.length === 0) {
    return;
}

...
```

File: renderer/nyaovim-app.ts [hunk 4]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+                        if (ch == 'v'  // visual mode
+                            || ch == 'V' // visual line mode
+                            || (ch == '^' && value[1] == 'V') // visual block mode
+                           ) {
+                            const command = '"+y';
+                            client.input(command);
+                        } else {
+                            // execute the default copy command
+                            const webContents = ThisBrowserWindow.webContents;
+                            webContents.copy();
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: I think default copy behavior (this else clause) is not needed because it's confusing.  Please simply ignore if Vim can't yank some text.

File: renderer/nyaovim-app.ts [hunk 5]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+                           ) {
+                            const command = '"+x';
+                            client.input(command);
+                        } else {
+                            // other modes
+                            const webContents = ThisBrowserWindow.webContents;
+
+                            // execute the default cut command
+                            webContents.cut();
+                        }
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: I think below is simpler rather than this `if` statement.

```javascript
const command = ch === 'n' ? 'ggVG' : '<Esc>ggVG';
client.input(command);
```

File: renderer/nyaovim-app.ts [hunk 6]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+            ipc.on('nyaovim:cut', (_: Electron.IpcRendererEvent) => {
+                // get current vim mode
+                var m = client.commandOutput('echo mode()');
+                m.then(value => {
+                    //  mode() returns a strange '\n' at the beginning, why?
+                    value = value.trim();
+                    if (value.length > 0) {
+                        const ch = value[0];
+
+                        if (ch == 'v'  // visual mode
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: Please always use `===` for comparison in JavaScript.  `==` has many pitfalls.

File: renderer/nyaovim-app.ts [hunk 7]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+                                // insert mode
+                                // gp will move cursor to the last of pasted content
+                                const command = '<esc>"+gpi';
+                                client.input(command);
+                            } else {
+                                // other modes
+                                const webContents = ThisBrowserWindow.webContents;
+
+                                // execute the default paste command
+                                webContents.paste();
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: As the same as above,  I think this default behavior is confusing.  Simply ignoring would be better.

File: renderer/nyaovim-app.ts [hunk 8]
```diff
@@ -164,6 +164,117 @@ Polymer({
...
+
+            ipc.on('nyaovim:paste', (_: Electron.IpcRendererEvent) => {
+                // get current vim mode
+                var m = client.commandOutput('echo mode()');
+                m.then(value => {
+                    //  mode() returns a strange '\n' at the beginning, why?
+                    value = value.trim();
+                    if (value.length > 0) {
+                        const ch = value[0];
+
```
Comment (rhysd) [inline renderer/nyaovim-app.ts]: Could you reduce the repeat of `client.input(command);` here?

```javascript
let command;

if (ch === 'v') {
    command = ...;
} else if (...) {
    ...
} else ...

if (command) {
    client.input(command);
}
```

File: renderer/nyaovim-app.ts (hunk 1 above)
Comment (haifengkao) [inline renderer/nyaovim-app.ts]: `client.eval('mode()')` doesn't work for visual block mode.

**Comment by haifengkao** [comment]
Done. Please check it out.

**Comment by rhysd** [comment]
@haifengkao 

Could you use `client.evel()` rather than `client.commandOutput()` like `client.eval('mode()')` ?  It's more suitable for evaluating Vim script expression because it can receive the value directly and does not need `trim()`.

**Comment by rhysd** [comment]
> client.eval('mode()') doesn't work for visual block mode.

I think it's because the returned value is not `"^V"` string in Vim script.  It's actual `^V` (ctrl + 'v') one character so we need to check it via `ch.charCodeAt({the char code for Ctrl+v})`.

**Comment by rhysd** [comment]
According to `:echo char2nr("\<C-v>")`, we can detect `^V` by below code:

```javascript
if (ch.charCodeAt(0) === 22) {
  // When visual block mode...
}
```

**Comment by haifengkao** [comment]
done. you are right about `charCodeAt`

**Comment by rhysd** [comment]
Nice work! Thank you 😄
